/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface Text3dMarquee {
    }
    interface TextGlow {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLText3dMarqueeElement extends Components.Text3dMarquee, HTMLStencilElement {
    }
    var HTMLText3dMarqueeElement: {
        prototype: HTMLText3dMarqueeElement;
        new (): HTMLText3dMarqueeElement;
    };
    interface HTMLTextGlowElement extends Components.TextGlow, HTMLStencilElement {
    }
    var HTMLTextGlowElement: {
        prototype: HTMLTextGlowElement;
        new (): HTMLTextGlowElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "text-3d-marquee": HTMLText3dMarqueeElement;
        "text-glow": HTMLTextGlowElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface Text3dMarquee {
    }
    interface TextGlow {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "text-3d-marquee": Text3dMarquee;
        "text-glow": TextGlow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "text-3d-marquee": LocalJSX.Text3dMarquee & JSXBase.HTMLAttributes<HTMLText3dMarqueeElement>;
            "text-glow": LocalJSX.TextGlow & JSXBase.HTMLAttributes<HTMLTextGlowElement>;
        }
    }
}
